---
title: "meta_analysis_NT"
output: html_document
date: '2022-03-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(metafor)
library(tidyverse)
library(kableExtra)
library(openxlsx)
```



```{r things_I_dont_know}
#if(!"tinytex" %in% rownames(installed.packages())) install.packages("tinytex")
#tinytex::install_tinytex()
#if(!"devtools" %in% rownames(installed.packages())) install.packages("devtools")
#devtools::install_github("crsh/papaja")
```

```{r functions}
######################################################################
#Converts from Student's t to Pearson's r
t_to_r <- function(t, n, k){sqrt(
  (t^2)/((t^2)+(n-1-k))
  )}


######################################################################
#Cohen's f-squared to r (Cohen, 1988; checked)
f2_to_r <- function(f2){
  sqrt(
    (f2)/(1+f2)
  )
}


######################################################################
#r to Fisher's z
#Fisher's z of r can be calculated using one of the following functions
#Equation 1:
r_to_fz <- function(r){
  (log((1+r)/(1-r)))/2
  }
#Equation 2:
atanh(0.439941345)
#Proving that both functions are the same 
r_to_fz (0.439941345) - atanh(0.439941345)


######################################################################
#variance of Fisher's z (checked)
var_fz <- function(n){1/(n-3)}
sqrt(var_fz(50))


######################################################################
#Standard error of Fisher's z (checked)
se_fz <- function(n)(sqrt(1/(n-3)))


######################################################################
#Confidence Interval for Fisher's z 
ci_fz <- function(fz, se_fz, cl){
  lower <- fz-(((qnorm(p = ((1-((1-cl)/2))), mean = 0, sd = 1)))*(se_fz))
  upper <- fz+(((qnorm(p = ((1-((1-cl)/2))), mean = 0, sd = 1)))*(se_fz))
  return(c(lower, upper))}


######################################################################
#Hybrid function that returns Fisher's z, variance of Fisher's z, Standard Error of Fisher's z, and confidence intervals 
r_to_fz.2 <- function(r, n, cl){
  r <- r
  n <- n
  fz <- (log((1+r)/(1-r)))/2
  var_fz <- (1/(n-3))
  se_fz <- sqrt(1/(n-3))
  lower_ci <- fz-(((qnorm(p = ((1-(1-cl)/2)), mean = 0, sd = 1)))*(se_fz))
  upper_ci <- fz+(((qnorm(p = ((1-(1-cl)/2)), mean = 0, sd = 1)))*(se_fz))
  return(data.frame(r, n, fz, var_fz, se_fz, lower_ci, upper_ci))
}
#Example 
r_to_fz.2(r = 0.778, n = 78, cl = .95)


######################################################################
#A function that convert Pearson's r to Fisher's z 
#Returns the effect size, variance, standard error, and confidence intervals for both Pearson's r and Fisher's z
rzr <- function(data, cl){
  data %>% mutate(fz = (log((1+r)/(1-r)))/2) %>% 
    mutate(fz.2 = atanh(r)) %>% 
    mutate(var_fz = 1/(n-3)) %>% 
    mutate(se_fz = sqrt(1/(n-3))) %>% 
    mutate(weight = 1/var_fz) %>% 
    mutate(CI_lower_fz = fz-(((qnorm(p = ((1-((1-cl)/2))), mean = 0, sd = 1)))*(se_fz))) %>% 
    mutate(CI_upper_fz = fz+(((qnorm(p = ((1-((1-cl)/2))), mean = 0, sd = 1)))*(se_fz))) %>% 
    mutate(var_r = (exp(2*var_fz)-1)/(exp(2*var_fz)+1)) %>% 
    mutate(se_r = (exp(2*se_fz)-1)/(exp(2*se_fz)+1)) %>% 
    mutate(CI_lower_r = (exp(2*CI_lower_fz)-1)/(exp(2*CI_lower_fz)+1)) %>% 
    mutate(CI_upper_r = (exp(2*CI_upper_fz)-1)/(exp(2*CI_upper_fz)+1))
}
######################################################################
#Fisher's z to r
#Function 1
fz_to_r <- function(fz){
  (exp(2*fz)-1)/(exp(2*fz)+1)
}

#Proving that both functions are the same 
fz_to_r(0.56) - tanh(0.56)


######################################################################
#Partial correlation 
pr <- function(r_ac, r_bc, r_ab.c){
  r_ab <- (r_ab.c*(sqrt((1-(r_ac^2))*(1-(r_bc^2)))))+(r_ac*r_bc)
  return(c(r_ab))}
pr(r_ab.c = 0.343110576, r_ac = 0.493963561, r_bc = 0.42)

######################################################################
time_converter <- function(min, d, m, y){
      mins <- ifelse(
    missing(min),
    ifelse(
      missing(d),
      ifelse(
        missing(m),
        y*525960,
        m*44560.5),
      d*1440),
    min*1)
    days <- ifelse(
    missing(d),
    ifelse(
      missing(min),
      ifelse(
        missing(m),
        y*365.25,
        m*30.4375),
      min/1440),
    d*1)
  months <- ifelse(
    missing(m),
    ifelse(
      missing(min), 
      ifelse(
        missing(d), 
        y*12, 
        d/30.4375),
      min/43830),
    m*1)
  years <- ifelse(
    missing(y),
    ifelse(
      missing(min), 
      ifelse(
        missing(d), 
        m/12, 
        d/365.25),
      min/525960),
    y*1)
  return(tibble(mins,days, months, years))
}

```



```{r son_and_hur.2020}
son_and_hur.2020_tib <- c(
  "son_and_hur.2020a", 
  "son_and_hur.2020b") %>% data.frame() %>% rename(., effect = .) %>% add_column(
    effect_description = c("Total Math Talk - Fall MA", "Total Maths Talk - Spring MA"),
    effect_id = c("Overall_Overall", "Overall_Overall"),
    year = c(2020, 2020),
    country = c("US", "US"),
    study_id = c("son_and_hur.2020", "son_and_hur.2020"),
    design = c("Correlational", "Correlational"),
    design.2 = c("Longitudinal_Correlational", "Longitudinal_Correlational"), 
    SES = c("Low", "Low"),
    main_language = c("English", "English"),
    deliverer_type = c("Parent", "Parent"),
    mothers = c(1, 1),
    white = c(0.500, 0.500), 
    female = c(0.47826087, 0.47826087),
    child_age_study_start = c(1717.284, 1717.284),
    child_age_NT_start = c(NA, NA),
    child_age_NT_mid = c(1793.378, 1793.378),
    child_age_NT_end = c(NA, NA),
    child_age_MA = c(1793.378, 2067.315),
    NT_measure_time = c(17.5, 17.5),
    time_between_NT_mid_MA = c(0, 273.937),
    intervention_dosage = c(NA, NA),
    NT_context = c("Home", "Home"),
    MA_context = c("School", "School"),
    NT_size = c(NA, NA),
    NT_size.1 = c("Overall", "Overall"),
    NT_type = c("Overall", "Overall"),
    NT_type.1 = c("Overall", "Overall"),
    NT_type.10 = c("Overall", "Overall"),
    MA_test = c("WJ_AP", "WJ_AP"),
    MA_measure = c("Overall", "Overall"),
    analysis = c("Zero_Order_Correlation", "Zero_Order_Correlation"),
    controlled_variables = c(0, 0),
    r = c(0.22, 0.21),
    n = c(29, 29))
```


```{r ramani_et_al.2015}
ramani_et_al.2015_tib <- c(
  "ramani_et_al.2015a", 
  "ramani_et_al.2015b", 
  "ramani_et_al.2015c", 
  "ramani_et_al.2015d",
  "ramani_et_al.2015e",
  "ramani_et_al.2015f",
  "ramani_et_al.2015g",
  "ramani_et_al.2015h",
  "ramani_et_al.2015i",
  "ramani_et_al.2015j",
  "ramani_et_al.2015k",
  "ramani_et_al.2015l") %>% data.frame() %>% rename(., effect = .) %>% add_column(
    effect_description = c("Counting and Number Identification - Verbal Counting", "Cardinality and Ordering  - Verbal Counting", "Counting and Number Identification - Number Identification", "Cardinality and Ordering - Number Identification", "Counting and Number Identification - Counting principles", "Cardinality and Ordering - Counting principles", "Counting and Number Identification - Enumeration and Cardinality", "Cardinality and Ordering - Enumeration and Cardinality", "Counting and Number Identification - Number Line Estimation", "Cardinality and Ordering - Number Line Estimation", "Counting and Number Identification - Magnitude Comparison", "Cardinality and Ordering - Magnitude Comparison"),
    effect_id = c("Overall_Counting", "Overall_Counting", "Overall_Number_Identification", "Overall_Number_Identification", "Overall_Counting", "Overall_Counting", "Overall_Cardinality", "Overall_Cardinality",  "Overall_Number_Line_Estimation",  "Overall_Number_Line_Estimation", "Overall_Quantity_Comparison", "Overall_Quantity_Comparison"),
    year = c(2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015),
    country = c("US", "US", "US", "US", "US", "US", "US", "US", "US", "US", "US", "US"),
    study_id = c("ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015", "ramani_et_al.2015"),
    design = c("Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational"),
    design.2 = c("Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational"), 
    SES = c("Low", "Low", "Low", "Low", "Low", "Low", "Low", "Low", "Low", "Low", "Low", "Low"),
    main_language = c("English", "English", "English", "English", "English", "English", "English", "English", "English", "English", "English", "English"),
    deliverer_type = c("Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver", "Caregiver"),
    mothers = c(0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788, 0.787878788),
    white = c(0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33, 0.33), 
    female = c(0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6),
    child_age_study_start = c(1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75),
    child_age_NT_start = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
    child_age_NT_mid = c(1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75, 1582.75),
    child_age_NT_end = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
    child_age_MA = c(1593.25, 1593.25, 1593.25, 1593.25, 1593.25, 1593.25, 1593.25, 1593.25, 1593.25, 1593.25, 1593.25, 1593.25),
    NT_measure_time = c(15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15),
    time_between_NT_mid_MA = c(10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5),
    intervention_dosage = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
    NT_context = c("School", "School", "School", "School", "School", "School", "School", "School", "School", "School", "School", "School"),
    MA_context = c("School", "School", "School", "School", "School", "School", "School", "School", "School", "School", "School", "School"),
    NT_size = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
    NT_size.1 = c("Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
    NT_type = c("Counting_and_Number_Identificaton", "Cardinality_and_Ordering", "Counting_and_Number_Identification", "Cardinality_and_Ordering", "Counting_and_Number_Identification", "Cardinality_and_Ordering", "Counting_and_Number_Identification", "Cardinality_and_Ordering", "Counting_and_Number_Identification", "Cardinality_and_Ordering", "Counting_and_Number_Identification", "Cardinality_and_Ordering"),
    NT_type.1 = c("Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
    NT_type.10 = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA),
    MA_test = c("Verbal_Counting", "Verbal_Counting", "Number_Identification", "Number_Identification", "Counting_Principles", "Counting_Principles", "Enumeration_and_Cardinality", "Enumeration_and_Cardinality", "Number_Line_Estimation", "Number_Line_Estimation", "Magnitude_Comparison", "Magnitude_Comparison"),
    MA_measure = c("Counting", "Counting", "Number_Identification", "Number_Identification", "Counting", "Counting", "Cardinality", "Cardinality", "Number_Line_Estimation", "Number_Line_Estimation", "Quantity_Comparison", "Quantity_Comparison"),
    analysis = c("Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order _orrelation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation"),
    controlled_variables = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
    r = c(-0.12, 0.11, -0.19, 0.10, 0.07, 0.17, -0.31, -0.03, 0.05, 0.37, 0.11, 0.39),
    n = c(33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33))
#ramani_et_al.2015_kable <- ramani_et_al.2015_tib %>% 
  #dplyr::mutate(dplyr::across(where(is.numeric), ~round(., 2))) %>% 
  #kable(format = "html", caption = "Ramani et al. (2015) effect sizes and associated inferential statistics", col.names = c("Effect id", "Effect Description", "Analysis", "Controlled variables","r", "n", "z", "Var of z", "SE of z", "Weight", "Lower CI for z", "Upper CI for z", "Var of r", "SE of r", "Lower CI for r", "Upper CI for r")) %>% kable_styling(full_width = T, position = "center") %>% row_spec(row = 0, extra_css = "border-bottom: 2px solid black;") #

```

```{r mutaf_yildiz et al.2018}
mutaf_yildiz_et_al.2018_tib <- c(
  "mutaf_yildiz_et_al.2018a", 
  "mutaf_yildiz_et_al.2018b"
  ) %>% data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("NT during book reading - Calculation skill", "NT during Lego playing - Calculation skill"),
      effect_id = c("Overall_Calculation", "Overall_Calculation"),
      year = c(2018, 2018),
      country = c("BE", "BE"),
      study_id = c("mutaf_yildiz_et_al.2018", "mutaf_yildiz_et_al.2018"),
      design = c("Correlational", "Correlational"),
      design.2 = c("Cross_sectional_Correlational", "Cross_sectional_Correlational"), 
      SES = c("Middle", "Middle"),
      main_language = c("Dutch", "Dutch"),
      deliverer_type = c("Parent", "Parent"),
      mothers = c(0.682, 0.682),
      white = c(NA, NA), 
      female = c(0.454545455, 0.454545455),
      child_age_study_start = c(2060.01, 2060.01),
      child_age_NT_start = c(NA, NA),
      child_age_NT_mid = c(2060.01, 2060.01),
      child_age_NT_end = c(NA, NA),
      child_age_MA = c(2060.01, 2060.01),
      NT_measure_time = c(5, 5),
      time_between_NT_mid_MA = c(0, 0),
      intervention_dosage = c(NA, NA),
      NT_context = c("Home", "Home"),
      MA_context = c("Home", "Home"),
      NT_size = c(NA, NA),
      NT_size.1 = c("Overall", "Overall"),
      NT_type = c("Overall", "Overall"),
      NT_type.1 = c("Overall", "Overall"),
      NT_type.10 = c("Overall", "Overall"),
      MA_test = c("TediMath", "TediMath"),
      MA_measure = c("Calculation", "Calculation"),
      analysis = c("Zero_Order_Correlation", "Zero_Order_Correlation"),
      controlled_variables = c(0, 0),
      r = c(-0.05, -0.35),
      n = c(44, 44)) 

```

```{r elliott_et_al.2017}
elliott_et_al.2017_tib <- c(
  "elliott_et_al.2017a") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("NT - TEMA-3"),
      effect_id = c("Overall_Overall"),
      year = c(2017),
      country = c("US"),
      study_id = c("elliott_et_al.2017"),
      design = c("Correlational"),
      design.2 = c("Cross_sectional_Correlational"), 
      SES = c("Middle"),
      main_language = c("English"),
      deliverer_type = c("Parent"),
      mothers = c(1),
      white = c(0.89), 
      female = c(0.434782609),
      child_age_study_start = c(2116.928),
      child_age_NT_start = c(NA),
      child_age_NT_mid = c(2116.928),
      child_age_NT_end = c(NA),
      child_age_MA = c(2116.928),
      NT_measure_time = c(10),
      time_between_NT_mid_MA= c(0),
      intervention_dosage = c(NA),
      NT_context = c("Lab"),
      MA_context = c("Lab"),
      NT_size = c("Overall"),
      NT_size.1 = c("Overall"),
      NT_type = c("Overall"),
      NT_type.1 = c("Overall"),
      NT_type.10 = c("Overall"),
      MA_test = c("TEMA_3"),
      MA_measure = c("Overall"),
      analysis = c("Zero_Order_Correlation"),
      controlled_variables = c(0),
      r = c(0.16),
      n = c(44))

```

```{r levine_et_al.2010}
levine_et_al.2010_tib <- c(
  "levine_et_al.2010a") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("NT - Point-to-X"),
      effect_id = c("Overall_Cardinality"), 
      year = c(2010),
      country = c("US"),
      study_id = c("a"),
      design = c("Correlational"),
      design.2 = c("Longitudinal_Correlational"), 
      SES = c("Middle"),
      main_language = c("English"),
      deliverer_type = c("Caregiver"),
      mothers = c(NA),
      white = c(0.704545455), 
      female = c(0.454545455),
      child_age_study_start = c(426.125),
      child_age_NT_start = c(426.125),
      child_age_NT_mid = c(669.625),
      child_age_NT_end = c(913.125),
      child_age_MA = c(1400.125),
      NT_measure_time = c(450),
      time_between_NT_mid_MA = c(730.5),
      intervention_dosage = c(NA),
      NT_context = c("Home"),
      MA_context = c(NA),
      NT_size = c("Overall"),
      NT_size.1 = c("Overall"),
      NT_type = c("Overall"),
      NT_type.1 = c("Overall"),
      NT_type.10 = c("Overall"),
      MA_test = c("Point_to_X"),
      MA_measure = c("Cardinality"),
      analysis = c("Zero Order Correlation"),
      controlled_variables = c(0),
      r = c(0.47),
      n = c(44))

```

```{r gunderson_and_levine.2011}
#Uncontrolling SES 
#Effect e: NT with present objects, small set predicting Point-to-X (Uncontrolled for SES)
pr(r_ab.c = 0.343110576, r_ac = 0.493963561, r_bc = 0.42)
#Effect f: NT without present objects, small set predicting Point-to-X (Uncontrolled for SES)
pr(r_ab.c = 0.188982236, r_ac = 0.493963561, r_bc = 0.40)
#Effect g: NT with present objects, large set predicting Point-to-X (Uncontrolled for SES)
pr(r_ab.c = 0.455710387, r_ac = 0.493963561, r_bc = 0.23)
#Effect h: NT without present objects, large set predicting Point-to-X (Uncontrolled for SES)
pr(r_ab.c = 0.178174161, r_ac = 0.493963561, r_bc = 0.06)

(0.4782052 + 0.3481842)/2
(0.4992211 + 0.184278)/2

gunderson_and_levine.2011_tib <- c(
  "gunderson_and_levine.2011a", 
  "gunderson_and_levine.2011b") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("Small NT predicting Point-to-X", "Large NT predicting Point-to-X"),
      year = c(2010, 2010),
      country = c("US", "US"),
      study_id = c("levine_et_al.2010", "levine_et_al.2010"),
      design = c("Correlational", "Correlational"),
      design.2 = c("Longitudinal_Correlational", "Longitudinal_Correlational"), 
      SES = c("Middle", "Middle"),
      main_language = c("English", "English"),
      deliverer_type = c("Caregiver", "Caregiver"),
      mothers = c(NA, NA),
      white = c(0.704545455, 0.704545455), 
      female = c(0.454545455, 0.454545455),
      child_age_study_start = c(426.125, 426.125),
      child_age_NT_start = c(426.125, 426.125),
      child_age_NT_mid = c(669.625, 669.625),
      child_age_NT_end = c(913.125, 913.125),
      child_age_MA = c(1400.125, 1400.125),
      NT_measure_time = c(450, 450),
      time_between_NT_mid_MA = c(730.5, 730.5),
      intervention_dosage = c(NA, NA),
      NT_context = c("Home", "Home"),
      MA_context = c(NA, NA),
      NT_size = c("Small", "Large"),
      NT_size.1 = c("Small", "Medium"),
      NT_type = c("Overall", "Overall"),
      NT_type.1 = c("Overall", "Overall"),
      NT_type.10 = c("Overall", "Overall"),
      MA_test = c("Point_to_X", "Point_to_X"),
      MA_measure = c("Cardinality", "Cardinality"),
      analysis = c("Calculated_manually", "Calculated_manually"),
      controlled_variables = c(0, 0),
      r = c(0.4131947, 0.3417495),
      n = c(44, 44))

```

```{r boonen_et_al.2011}
boonen_et_al.2011_tib <- c(
  "boonen_et_al.2011a", 
  "boonen_et_al.2011b", 
  "boonen_et_al.2011c", 
  "boonen_et_al.2011d", 
  "boonen_et_al.2011e", 
  "boonen_et_al.2011f", 
  "boonen_et_al.2011g", 
  "boonen_et_al.2011h",
  "boonen_et_al.2011i") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("Calculation NT predicting AD MA", "Conventional Nominatives NT predicting AD MA", "Conventional Nominatives NT predicting AD MA", "Conventional Nominatives predicting ENT-R", "Counting NT predicting ENT-R", "Ordering NT predicting ENT-R", "Number Symbols NT predicting ENT-R", "Cardinality NT predicting quantity comparison task", "Calculation NT predicting Cardinality"),
      effect_id = c("Calculation_Overall", "Conventional_Nominatives_Overall", "Conventional_Nominatives_Overall", "Conventional_Nominatives_Overall", "Counting_Overall", "Ordering_Overall", "Number_Identification_Overall", "Cardinality_Quantity_Comparison", "Calculation_Number_Identification"),
      year = c(2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011,2011),
      country = c("NE", "NE", "NE", "NE", "NE", "NE", "NE", "NE", "NE"),
      study_id = c("boonen_et_al.2011", "boonen_et_al.2011", "boonen_et_al.2011", "boonen_et_al.2011", "boonen_et_al.2011", "boonen_et_al.2011", "boonen_et_al.2011", "boonen_et_al.2011", "boonen_et_al.2011"),
      design = c("Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational"),
      design.2 = c("Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational"), 
      SES = c("Middle", "Middle", "Middle", "Middle", "Middle", "Middle", "Middle", "Middle", "Middle"),
      main_language = c("Dutch", "Dutch", "Dutch", "Dutch", "Dutch", "Dutch", "Dutch", "Dutch", "Dutch"),
      deliverer_type = c("Teacher", "Teacher", "Teacher", "Teacher", "Teacher", "Teacher", "Teacher", "Teacher", "Teacher"),
      mothers = c(NA, NA, NA, NA, NA, NA, NA, NA, NA),
      white = c(NA, NA, NA, NA, NA, NA, NA, NA, NA), 
      female = c(0.501992032, 0.501992032, 0.501992032, 0.501992032, 0.501992032, 0.501992032, 0.501992032, 0.501992032, 0.501992032),
      child_age_study_start = c(1899.3, 1899.3, 1899.3, 1899.3, 1899.3, 1899.3, 1899.3, 1899.3, 1899.3),
      child_age_NT_start = c(NA, NA, NA, NA, NA, NA, NA, NA, NA),
      child_age_NT_mid = c(NA, NA, NA, NA, NA, NA, NA, NA,  NA),
      child_age_NT_end = c(NA, NA, NA, NA, NA, NA, NA, NA,  NA),
      child_age_MA = c(NA, NA, NA, NA, NA, NA, NA, NA,  NA),
      NT_measure_time = c(60, 60, 60, 60, 60, 60, 60, 60, 60),
      time_between_NT_mid_MA = c(NA, NA, NA, NA, NA, NA, NA, NA,  NA),
      intervention_dosage = c(NA, NA, NA, NA, NA, NA, NA, NA, NA),
      NT_context = c("School", "School", "School", "School", "School", "School", "School", "School", "School"),
      MA_context = c("School", "School", "School", "School", "School", "School", "School", "School", "School"),
      NT_size = c("Overall", "Overall","Overall","Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
      NT_size.1 = c("Overall", "Overall","Overall","Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
      NT_type = c("Calculation", "Conventional_Nominatives", "Conventional_Nominatives","Conventional_Nominatives", "Counting", "Ordering", "Number_Identification", "Cardinality", "Calculation"),
      NT_type.1 = c("Calculation", "Conventional_Nominatives", "Conventional_Nominatives","Conventional_Nominatives", "Counting", "Ordering", "Number_Identification", "Cardinality", "Calculation"),
      NT_type.10 = c("Calculation", "Conventional_Nominatives", "Conventional_Nominatives","Conventional_Nominatives", "Counting", "Ordering", "Number_Identification", "Cardinality", "Calculation"),
      MA_test = c("AD_Number_Sense", "AD_Number_Sense", "AD_Number_Sense", "ENT_R", "ENT_R","ENT_R", "ENT_R", "Quantity_Comparison_Task", "Number_Naming_Task"),
      MA_measure = c("Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Quantity_Comparison", "Number_Identification"),
      analysis = c("Multiple_Regression", "Multiple_Regression", "Multiple_Regression", "Multiple_Multilevel_Regression", "Multiple_Multilevel_Regression", "Multiple_Multilevel_Regression", "Multiple_Multilevel_Regression", "Multiple_Regression", "Multiple_Regression"),
      controlled_variables = c(5, 5, 2, 7, 7, 7, 7, 2, 3),
      r = c(-0.1394642, 0.2006911, 0.1733843, 0.2875227, -0.1124199, -0.1356559, -0.1237494, 0.1187748, -0.1475598),
      n = c(251, 251, 251, 251, 251, 251, 251, 251, 251))

```


```{r susperreguy_and_davis_kean.2016}
susperreguy_and_davis_kean.2016_tib <- c(
  "susperreguy_and_davis_kean.2016a") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("Proportion of Cumulative Math Talk - TEMA-3"),
      effect_id = c("Overall_Overall"),
      year = c(2016),
      country = c("US"),
      study_id = c("susperreguy_and_davis_kean.2016"),
      design = c("Correlational"),
      design.2 = c("Longitudinal_Correlational"), 
      SES = c("Middle"),
      main_language = c("English"),
      deliverer_type = c("Parent"),
      mothers = c(1),
      white = c(0.686), 
      female = c(0.314285714),
      child_age_study_start = c(1643.625),
      child_age_NT_start = c(1643.625),
      child_age_NT_mid = c(1647.125),
      child_age_NT_end = c(1650.625),
      child_age_MA = c(2008.875),
      NT_measure_time = c(240),
      time_between_NT_mid_MA = c(365.25),
      intervention_dosage = c(NA),
      NT_context = c("Home"),
      MA_context = c(NA),
      NT_size = c("Overall"),
      NT_size.1 = c("Overall"),
      NT_type = c("Overall"),
      NT_type.1 = c("Overall"),
      NT_type.10 = c("Overall"),
      MA_test = c("TEMA_3"),
      MA_measure = c("Overall"),
      analysis = c("Zero_Order_Correlation"),
      controlled_variables = c(0),
      r = c(0.17),
      n = c(33))

```

```{r casey_et_al.2018}
casey_et_al.2018_tib <- c(
  "casey_et_al.2018a", 
  "casey_et_al.2018b",
  "casey_et_al.2018c", 
  "casey_et_al.2018d", 
  "casey_et_al.2018e", 
  "casey_et_al.2018f", 
  "casey_et_al.2018g", 
  "casey_et_al.2018h") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("Identify numerals NT - WJ Applied Problems at 4.5 yrs", "Identify numerals NT - WJ Applied Problems at 1st grade", "One-to-one counting NT - WJ Applied Problems at 4.5 yrs", "One-to-one counting NT - WJ Applied Problems at 1st grade", "Label sets NT - WJ Applied Problems at 4.5 yrs", "Label sets NT - WJ Applied Problems at 1st grade", "Sum of numerical supports NT - WJ Applied Problems at 4.5 yrs", "Sum of numerical supports NT - WJ Applied Problems at 1st grade"),
      effect_id = c("Number_Identification_Overall", "Number_Identification_Overall", "Counting_Overall", "Counting_Overall", "Cardinality_Overall", "Cardinality_Overall", "Overall_Overall", "Overall_Overall" ), 
      year = c(2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018),
      country = c("US", "US", "US", "US", "US", "US", "US", "US"),
      study_id = c("casey_et_al.2018", "casey_et_al.2018", "casey_et_al.2018", "casey_et_al.2018", "casey_et_al.2018", "casey_et_al.2018", "casey_et_al.2018", "casey_et_al.2018"),
      design = c("Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational", "Correlational"),
      design.2 = c("Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational", "Longitudinal_Correlational"), 
      SES = c("Middle", "Middle", "Middle", "Middle", "Middle", "Middle", "Middle", "Middle"),
      main_language = c("English", "English", "English", "English", "English", "English", "English", "English"),
      deliverer_type = c("Parent", "Parent", "Parent", "Parent", "Parent", "Parent", "Parent", "Parent"),
      mothers = c(1, 1, 1, 1, 1, 1, 1, 1),
      white = c(0.84, 0.84, 0.84, 0.84, 0.84, 0.84, 0.84, 0.84), 
      female = c(0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45),
      child_age_study_start = c(NA, NA, NA, NA, NA, NA, NA, NA),
      child_age_NT_start = c(NA, NA, NA, NA, NA, NA, NA, NA),
      child_age_NT_mid = c(1095.75, 1095.75, 1095.75, 1095.75, 1095.75, 1095.75, 1095.75, 1095.75),
      child_age_NT_end = c(NA, NA, NA, NA, NA, NA, NA, NA),
      child_age_MA = c(1643.625, 2374.125, 1643.625, 2374.125, 1643.625, 2374.125, 1643.625, 2374.125),
      NT_measure_time = c(10, 10, 10, 10, 10, 10, 10, 10),
      time_between_NT_mid_MA = c(547.875, 1278.375, 547.875, 1278.375, 547.875, 1278.375, 547.875, 1278.375),
      intervention_dosage = c(NA, NA, NA, NA, NA, NA, NA, NA),
      NT_context = c("Lab", "Lab", "Lab", "Lab", "Lab", "Lab", "Lab", "Lab"),
      MA_context = c(NA, NA, NA, NA, NA, NA, NA, NA),
      NT_size = c("Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
      NT_size.1 = c("Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
      NT_type = c("Number_Identification", "Number_Identification", "Counting", "Counting", "Cardinality", "Cardinality", "Overall", "Overall"),
      NT_type.1 = c("Number_Identification", "Number_Identification", "Counting", "Counting", "Cardinality", "Cardinality", "Overall", "Overall"),
      NT_type.10 = c("Number_Identification", "Number_Identification", "Counting", "Counting", "Cardinality", "Cardinality", "Overall", "Overall"),
      MA_test = c("WJ_AP", "WJ_AP", "WJ_AP", "WJ_AP", "WJ_AP", "WJ_AP", "WJ_AP", "WJ_AP"),
      MA_measure = c("Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
      analysis = c("Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation","Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation", "Zero_Order_Correlation"),
      controlled_variables = c(0, 0, 0, 0, 0, 0, 0, 0),
      r = c(-0.02, -0.04, -0.01, 0.05, 0.30, 0.33, 0.06, 0.07),
      n = c(99, 99, 99, 99, 99, 99, 99, 99))

```

```{r zippert_et_al.2019}
zippert_et_al.2019_tib <- c(
  "zippert_et_al.2019a", 
  "zippert_et_al.2019b", 
  "zippert_et_al.2019c", 
  "zippert_et_al.2019d",
  "zippert_et_al.2019e",
  "zippert_et_al.2019f",
  "zippert_et_al.2019g",
  "zippert_et_al.2019h") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("Counting NT - Rote Counting", "Number Identification NT - Rote Counting", "Cardinality NT - Rote Counting", "Quantity Comparison NT - Rote Counting", "Counting NT - Number Line Estimation", "Number Identification NT - Number Line Estimation", "Cardinality NT - Number Line Estimation", "Quantity Comparison NT - Number Line Estimation"),
      effect_id = c("Counting_Counting", "Number_Identification_Counting", "Cardinality_Counting", "Quantity_Comparison_Counting", "Counting_Number_Line_Estimation", "Number_Identification_Number_Line_Estimation", "Cardinality_Number_Line_Estimation", "Quantity_Comparison_Number_Line_Estimation"), 
      year = c(2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019),
      country = c("US", "US", "US", "US", "US", "US", "US", "US"),
      study_id = c("zippert_et_al.2019", "zippert_et_al.2019", "zippert_et_al.2019", "zippert_et_al.2019", "zippert_et_al.2019", "zippert_et_al.2019", "zippert_et_al.2019", "zippert_et_al.2019"),
      design = c("Experimental", "Experimental", "Experimental", "Experimental", "Experimental", "Experimental", "Experimental", "Experimental"),
      design.2 = c("Short_term_Experimental", "Short_term_Experimental", "Short_term_Experimental", "Short_term_Experimental", "Short_term_Experimental", "Short_term_Experimental", "Short_term_Experimental", "Short_term_Experimental"), 
      SES = c(NA, NA, NA, NA, NA, NA, NA, NA),
      main_language = c("English", "English", "English", "English", "English", "English", "English", "English"),
      deliverer_type = c("Parent", "Parent", "Parent", "Parent", "Parent", "Parent", "Parent", "Parent"),
      mothers = c(0.61, 0.61, 0.61, 0.61, 0.61, 0.61, 0.61, 0.61),
      white = c(NA, NA, NA, NA, NA, NA, NA, NA), 
      female = c(0.41, 0.41, 0.41, 0.41, 0.41, 0.41, 0.41, 0.41),
      child_age_study_start = c(1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99),
      child_age_NT_start = c(1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99),
      child_age_NT_mid = c(1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99),
      child_age_NT_end = c(1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99),
      child_age_MA = c(1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99, 1835.99),
      NT_measure_time = c(NA, NA, NA, NA, NA, NA, NA, NA),
      time_between_NT_mid_MA = c(0, 0, 0, 0, 0, 0, 0, 0),
      intervention_dosage = c(0.006944444, 0.006944444, 0.006944444, 0.006944444, 0.006944444, 0.006944444, 0.006944444, 0.006944444),
      NT_context = c("Museum", "Museum", "Museum", "Museum", "Museum", "Museum", "Museum", "Museum"),
      MA_context = c("Museum", "Museum", "Museum", "Museum", "Museum", "Museum", "Museum", "Museum"),
      NT_size = c(NA, NA, NA, NA, NA, NA, NA, NA),
      NT_size.1 = c("Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"),
      NT_type = c("Counting", "Number_Identification", "Cardinality", "Quantity_Comparison", "Counting", "Number_Identification", "Cardinality", "Quantity_Comparison"),
      NT_type.1 = c("Counting", "Number_Identification", "Cardinality", "Quantity_Comparison", "Counting", "Number_Identification", "Cardinality", "Quantity_Comparison"),
      NT_type.10 = c("Counting", "Number_Identification", "Cardinality", "Quantity_Comparison", "Counting", "Number_Identification", "Cardinality", "Quantity_Comparison"),
      MA_test = c("Verbal_Counting", "Verbal_Counting", "Verbal_Counting", "Verbal_Counting", "Number_Line_Estimation", "Number_Line_Estimation", "Number_Line_Estimation", "Number_Line_Estimation"),
      MA_measure = c("Counting", "Counting", "Counting", "Counting", "Number_Line_Estimation", "Number_Line_Estimation", "Number_Line_Estimation", "Number_Line_Estimation"),
      analysis = c("Partial_Correlation", "Partial_Correlation", "Partial_Correlation", "Partial_Correlation", "Partial_Correlation", "Partial_Correlation", "Partial_Correlation", "Partial_Correlation"),
      controlled_variables = c(2, 2, 2, 2, 2, 2, 2, 2),
      r = c(-0.39, 0.01, -0.05, -0.06, 0.31, -0.01, -0.17, -0.17),
      n = c(25, 25, 25, 25, 25, 25, 25, 25))
```

```{r thippana_et_al.2020}
thippana_et_al.2020_tib <- c(
  "thippana_et_al.2020a", 
  "thippana_et_al.2020b") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("Home NT proportion - TEMA-3 ", "Lab NT proportion - TEMA-3"),
      effect_id = c("Overall_Overall", "Overall_Overall"),
      year = c(2020, 2020),
      country = c(NA, NA),
      study_id = c("thippana_et_al.2020", "thippana_et_al.2020"),
      design = c("Correlational", "Correlational"),
      design.2 = c("Longitudinal_Correlational", "Longitudinal_Correlational"), 
      SES = c("Middle",  "Middle"),
      main_language = c("English", "English"),
      deliverer_type = c("Parent", "Parent"),
      mothers = c(0.94, 0.94),
      white = c(0.85, 0.85), 
      female = c(0.484536082, 0.484536082),
      child_age_study_start = c(1430.562, 1430.562),
      child_age_NT_start = c(NA, NA),
      child_age_NT_mid = c(1446.172, 1446.172),
      child_age_NT_end = c(NA, NA),
      child_age_MA = c(1492.442, 1492.442),
      NT_measure_time = c(30, 20),
      time_between_NT_mid_MA = c(46.27, 46.27),
      intervention_dosage = c(NA, NA),
      NT_context = c("Home", "Lab"),
      MA_context = c("Lab", "Lab"),
      NT_size = c(NA, NA),
      NT_size.1 = c("Overall", "Overall"),
      NT_type = c("Overall", "Overall"),
      NT_type.1 = c("Overall", "Overall"),
      NT_type.10 = c("Overall", "Overall"),
      MA_test = c("TEMA_3", "TEMA_3"),
      MA_measure = c("Overall", "Overall"),
      analysis = c("Zero_Order_Correlation", "Zero_Order_Correlation"),
      controlled_variables = c(0, 0),
      r = c(0.20, 0.11),
      n = c(81, 81))

```

```{r gibson_et_al.2020}
gibson_et_al.2020_tib <- c(
  "gibson_et_al.2020a", 
  "gibson_et_al.2020b") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("Small Number Book vs Control", "Large Number vs Control"),
      effect_id = c("Overall_Number_Knowledge", "Overall_Number_Knowledge"),
      year = c(2020, 2020),
      country = c("US", "US"),
      study_id = c("gibson_et_al.2020", "gibson_et_al.2020"),
      design = c("Experimental", "Experimental"),
      design.2 = c("Long_term_Experimental", "Long_term_Experimental"), 
      SES = c("Middle", "Middle"),
      main_language = c("English", "English"),
      deliverer_type = c("Parent", "Parent"),
      mothers = c(NA, NA),
      white = c(0.52, 0.52), 
      female = c(0.52, 0.52),
      child_age_study_start = c(1132.275, 1132.275),
      child_age_NT_start = c(1132.275, 1132.275),
      child_age_NT_mid = c(1148.77, 1148.77),
      child_age_NT_end = c(1165.265, 1165.265),
      child_age_MA = c(1165.265, 1165.265),
      NT_measure_time = c(NA, NA),
      time_between_NT_mid_MA = c(16.495, 16.495),
      intervention_dosage = c(32.99, 32.99),
      NT_context = c("Home", "Home"),
      MA_context = c("Lab", "Lab"),
      NT_size = c("Small", "Large"),
      NT_size.1 = c("Small", "Large"),
      NT_type = c("Counting_and_Labelling", "Counting_and_Labelling"),
      NT_type.1 = c("Overall", "Overall"),
      NT_type.10 = c(NA, NA),
      MA_test = c("Give_N", "Give_N"),
      MA_measure = c("Number_Knowledge", "Number_Knowledge"),
      analysis = c("Pairwise_t", "Pairwise_t"),
      controlled_variables = c(0, 0),
      r = c(0.3224328, 0.069597355),
      n = c(97, 97))

```

```{r silver_et_al.2021}
silver_et_al.2021_tib <- c(
  "silver_et_al.2021a") %>% 
  data.frame() %>% rename(., effect = .) %>% 
    add_column(
      effect_description = c("NT - MA"),
      effect_id = c("Overall_Overall"),
      year = c(2021),
      country = c("US"),
      study_id = c("silver_et_al.2021"),
      design = c("Correlational"),
      design.2 = c("Cross_sectional_Correlational"), 
      SES = c("Middle"),
      main_language = c("English"),
      deliverer_type = c("Parent"),
      mothers = c(0.95),
      white = c(0.8), 
      female = c(0.479674797),
      child_age_study_start = c(1430.562),
      child_age_NT_start = c(1430.562),
      child_age_NT_mid = c(1430.562),
      child_age_NT_end = c(1430.562),
      child_age_MA = c(1430.562),
      NT_measure_time = c(10),
      time_between_NT_mid_MA = c(0),
      intervention_dosage = c(NA),
      NT_context = c("Lab"),
      MA_context = c("Lab"),
      NT_size = c("Overall"),
      NT_size.1 = c("Overall"),
      NT_type = c("Overall"),
      NT_type.1 = c("Overall"),
      NT_type.10 = c("Overall"),
      MA_test = c("TEMA_3"),
      MA_measure = c("Overall"),
      analysis = c("Zero_Order_Correlation"),
      controlled_variables = c(0),
      r = c(0.04),
      n = c(123))



#lower_ci <- fz-(((qnorm(p = ((1-(1-cl)/2)), mean = 0, sd = 1)))*(se_fz))
#qnorm(p = ((1-(1-cl)/2)))
#1-((1-0.95)/2)
#1-pt(q = 1.886838378, df = 113)
#qt(p = 0.975, df = 113)
#qnorm(p = 0.975)
#-(-0.01 - 0.10)/qt(p = 0.975, df = 121)
#(0.20 - 0.10)/qt(p = 0.975, df = 121)
#((0.20 - 0.10)/qt(p = 0.975, df = 121) + (-(-0.01 - 0.10)/qt(p = 0.975, df = 121)))/2
#-(-0.16 - (-0.06))/qt(p = 0.975, df = 121)
#(0.03 -(-0.06))/qt(p = 0.975, df = 121)
#((-(-0.16 - (-0.06))/qt(p = 0.975, df = 121))+((0.03 -(-0.06))/qt(p = 0.975, df = 121)))/2
#qt(p = (1-0.038), df = 121)
#0.10/qt(p = (1-0.038), df = 121)
#qt(p = (1-0.0815), df = 121)
#-(-0.06/qt(p = (1-0.0815), df = 121))
#0.1 - (1.979764 * 0.05051108)
#sqrt((1.2503772 ^2)/((1.2503772^2)+121))

```

```{r constructing_meta_tib}
meta_tib.p1 <- rbind(
  levine_et_al.2010_tib, 
  boonen_et_al.2011_tib,
  ramani_et_al.2015_tib,
  susperreguy_and_davis_kean.2016_tib,
  elliott_et_al.2017_tib, 
  casey_et_al.2018_tib,
  mutaf_yildiz_et_al.2018_tib, 
  zippert_et_al.2019_tib,
  son_and_hur.2020_tib,
  thippana_et_al.2020_tib, 
  gibson_et_al.2020_tib, 
  silver_et_al.2021_tib) 

meta_tib <- escalc(measure = "ZCOR", ri = r, ni = n, data = meta_tib.p1) %>% data.frame() %>% 
    mutate(
    effect = as.factor(effect),
    effect_description = as.character(effect_description),
    effect_id = as.factor(effect_id),
    year = as.numeric(year),
    country = as.factor(country),
    study_id = as.factor(study_id),
    design = as.factor(design),
    design.2 = as.factor(design.2),
    SES = as.factor(SES),
    main_language = as.factor(main_language),
    deliverer_type = as.factor(deliverer_type),
    mothers = as.numeric(mothers),
    white = as.numeric(white),
    female = as.numeric(female),
    child_age_study_start = as.numeric(child_age_study_start),
    child_age_NT_start = as.numeric(child_age_NT_start),
    child_age_NT_mid = as.numeric(child_age_NT_mid),
    child_age_NT_end = as.numeric(child_age_NT_end),
    child_age_MA = as.numeric(child_age_MA),
    NT_measure_time = as.numeric(NT_measure_time),
    time_between_NT_mid_MA = as.numeric(time_between_NT_mid_MA),
    intervention_dosage = as.numeric(intervention_dosage),
    NT_context = as.factor(NT_context),
    MA_context = as.factor(MA_context),
    NT_size = as.factor(NT_size),
    NT_size.1 = as.factor(NT_size.1),
    NT_type = as.factor(NT_type),
    NT_type.1 = as.factor(NT_type.1),
    NT_type.10 = as.factor(NT_type.10),
    MA_test = as.factor(MA_test),
    MA_measure = as.factor(MA_measure),
    analysis = as.factor(analysis),
    controlled_variables = as.numeric(controlled_variables),
    r = as.numeric(r),
    n = as.numeric(n)) %>% 
  dplyr::mutate(
    main_language = forcats::fct_relevel(main_language, "Dutch", "English"),
    NT_type.1 = forcats::fct_relevel(NT_type.1, "Calculation", "Cardinality", "Conventional_Nominatives", "Counting", "Number_Identification", "Ordering",  "Quantity_Comparison", "Overall"),
    NT_type.10 = forcats::fct_relevel(NT_type.10,"Calculation", "Cardinality", "Conventional_Nominatives", "Counting", "Number_Identification", "Ordering",  "Quantity_Comparison", "Overall"),
    MA_context = forcats::fct_relevel(MA_context, "Home", "Lab", "School", "Museum"),
    MA_measure = forcats::fct_relevel(MA_measure, "Calculation", "Cardinality", "Counting", "Number_Identification", "Number_Knowledge", "Number_Line_Estimation", "Quantity_Comparison", "Overall"),
    NT_context = forcats::fct_relevel(NT_context, "Home", "Lab", "School", "Museum")) %>% 
  select(-NT_size.1) 


#REPORT TABLEZ
#The number of effects in each study
num_eff_tib <- meta_tib %>% select(study_id, year) %>% group_by(study_id) %>% summarise(effects = n()) %>% add_column(as.tibble(str_sub(.$study_id, - 4, - 1))) %>% rename(year = value) %>% arrange(year) %>% select(study_id, effects)
num_eff_tib 

#Stem and leaf diagram
stem(meta_tib$yi) 


#Export data 
#write.xlsx(meta_tib, "meta_tib.xlsx", overwrite = T)
```


```{r random_effect_meta_analysis}
#Random-effect meta-analysis
re_meta_model <- rma(yi = yi, vi = vi, data = meta_tib, method  = "DL")
re_meta_model
#Forest Plot
forest(re_meta_model, addpred = T, header = T)

rma(yi = yi, vi = vi, data = meta_tib, method  = "FE")


#Funnel plot
funnel(re_meta_model)


#Prediction
predict(re_meta_model, transf = transf.ztor, digits = 5)

#Gosh Plot 
plot(gosh(re_meta_model, subset = 30000), out = 10)

#RESULTS
# Fisher's z = 0.0596
```


```{r ml_meta_analysis}
#2-level model (This is basically an RE model)
ml_meta_model.2lre <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "ML", test = "t",
                        random = ~ 1 | effect)
ml_meta_model.2lre %>% summary()
ml_meta_model.2lre

#2-level meta-analysis
ml_meta_model.2l <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                        random = ~ 1 | study_id)
ml_meta_model.2l

#3-level meta-analysis
ml_meta_model.3l <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "ML", test = "t",
                        random = ~ 1 | study_id/effect)
ml_meta_model.3l %>% summary()
ml_meta_model.3l


#Comparing all the models
fitstats(re_meta_model, ml_meta_model.2lre, ml_meta_model.2l, ml_meta_model.3l)

#Selecting the model 
ml_meta_model.3l
#3-level model is selected because this model structure is based on theory (e.g. Cheung, 2019)



#Outlier analysis for the 3-level model (RESULTS: NO OUTLIERS)
#3-level model
#Cook's d at level 2 (The Effect level)
ml_meta_model.3l_cooks.d_lev2 <- cooks.distance(ml_meta_model.2lre, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% tibble() %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_cooks.d_lev2
plot(cooks.distance(ml_meta_model.2lre, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect), type="o", pch=19, xlab="Observed Outcome", ylab="Cook's Distance")
#RESULTS 
#-- All Cook's distances are well below 1

#Cook's d at level 3 (The Study level)
ml_meta_model.3l_cooks.d_lev3 <- cooks.distance(ml_meta_model.2lre, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% tibble() %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_cooks.d_lev3 
plot(cooks.distance(ml_meta_model.2lre, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id), type="o", pch=19, xlab="Observed Outcome", ylab="Cook's Distance")
#RESULTS 
#-- All Cook's distances are well below 1



#Forest plots
forest(ml_meta_model.3l, addpred = T, header = T)
forest(ml_meta_model.2lre, addpred = T, header = T)


```

```{r robust_ml_meta_analysis}
#Clustered Robust SE
#robust.rma.mv(ml_meta_model.3l, cluster = meta_tib$effect, clubSandwich = T)
#Results 
#-- No major discrepancies 
#Conclusion 
#-- Use the original model 

#Bubble plot 
#regplot(meta_model, xlab = "x label", xlim = c(-, -), predlim= c(), transf = )


#meta_test <- function(data){
  #para_estimate <- data$b
  #within_study_var <- data$se^2
 # between_study_var <- data$sigma2
  #total_var = within_study_var + between_study_var
  #t <- para_estimate/sqrt(total_var)
  #p <- pt(q = t, df = data$k -1, lower.tail = F)*2
  #return(tibble(para_estimate, within_study_var, between_study_var, total_var, t, p))
#}

#meta_test(data = ml_meta_model)

```

```{r codes_for_outlier_diagnostics}
#cooks.distance(model, progbar=FALSE, cluster,
               ##reestimate=TRUE, parallel="no", ncpus=1, cl, ...)

# S3 method for rma.mv
#dfbetas(model, progbar=FALSE, cluster,
        #reestimate=TRUE, parallel="no", ncpus=1, cl, ...)

# S3 method for rma.mv
#hatvalues(model, type="diagonal", ...)
```

```{r moderator_analysis_main_language}
#Checking the levels 
levels(meta_tib$main_language)

#Setting contrast weights
english_vs_dutch <- c(-1/2, 1/2)
contrasts(meta_tib$main_language) <- english_vs_dutch



#Moderator analysis
#----------------------------------------------------------------------------------------------------
#3-level model
ml_meta_model.3l_mod_main_language <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "ML", test = "t",
                                          mods = ~ main_language,
                                          random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_main_language

#2-level re
ml_meta_model.2lre_mod_main_language <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "ML", test = "t",
                                          mods = ~ main_language,
                                          random = ~ 1 | effect)
ml_meta_model.2lre_mod_main_language

#2-level model 
ml_meta_model.2l_mod_main_language <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "ML", test = "t",
                                          mods = ~ main_language,
                                          random = ~ 1 | study_id)
ml_meta_model.2l_mod_main_language

#--RESULTS
#-- Only the 2-level model is significant


#Visualize 
regplot(ml_meta_model.3l_mod_main_language, xlab = "Language")





#Outlier Analysis
#Cook's d

#3-level model 
#Level 2
ml_meta_model.3l_mod_main_language_cooks.d_lev.2 <- cooks.distance(ml_meta_model.3l_mod_main_language, progbar=FALSE,
               reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% tibble() %>% rename(., cooks.d = .) %>% add_column(select(drop_na(data = meta_tib, main_language), effect)) %>% select(effect, cooks.d) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_main_language_cooks.d_lev.2 
#RESULTS
#No influential cases

#Level 3
ml_meta_model.3l_mod_main_language_cooks.d_lev.3 <- cooks.distance(ml_meta_model.3l_mod_main_language, progbar=FALSE,
               reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% tibble() %>% rename(., cooks.d = .) %>% add_column(num_eff_tib$study_id) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_main_language_cooks.d_lev.3
#RESULTS
#No outlier 

#DFBETAS
#3-level model
#Effect level 
dfbetas(ml_meta_model.3l_mod_main_language, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$effect) %>% 
  add_column(select(drop_na(data = meta_tib, main_language), effect)) %>% 
  select(effect, intrcpt, main_language1) %>% 
  mutate(absDFBETAS = abs(main_language1)) %>% 
  arrange(desc(absDFBETAS))
#DFBETAS RESULTS
#-- All DFBETAS are well below 1

#Effect level 
dfbetas_mod_main_language.p1 <- dfbetas(ml_meta_model.3l_mod_main_language, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$study_id) %>% 
  select(effect, intrcpt, main_language1) %>% 
  mutate(absDFBETAS = abs(main_language1)) %>% 
  arrange(desc(absDFBETAS))
#DFBETAS RESULTS
#-- All DFBETAS are well below 1
dfbetas_mod_main_language.p2 <- as.data.frame(dfbetas_mod_main_language.p1)
dfbetas_mod_main_language.p2$study_id <- rownames(dfbetas_mod_main_language.p1)

dfbetas_mod_main_language <- dfbetas_mod_main_language.p2 %>% select(study_id, intrcpt, main_language1) %>% mutate(absDFBETAS = abs(main_language1)) %>% arrange(desc(absDFBETAS))
dfbetas_mod_main_language 
#RESULTS 
#1 influential study
#Boonen



#CRAP 
#----------------------------------------------------------------------------------------------------

#Cook's d plot using ggplot
#ggplot(data = main_language_mod_cooks.d) + 
  #geom_col(mapping = aes(x = Effect_no, y = cooks.d),  width = 0.3, fill = "black")  + 
 # scale_y_continuous(expand = c(0,0), limits = c(0, 1.5)) +
 # scale_x_continuous(breaks = seq(1, 40, by = 1)) +
  #theme_classic()

#Cook's d plot using plot
#plot(cooks.distance(ml_meta_model_mod_main_language, progbar=FALSE,
               #reestimate=TRUE, parallel="no", ncpus=1), type="o", pch=19, xlab="Observed Outcome", ylab="Cook's Distance")

# Hatvalues 
#hatvalues(ml_meta_model_mod_main_language, type = "diagonal")

1#Re-run the analysis with the effects filtered out
#rma.mv(yi = yi, V = vi, data = filter(meta_tib, effect != c("boonen_et_al.2011b", "boonen_et_al.2011d")), struct = "CS", method = "ML", test = "t",mods = ~ main_language,random = ~ 1 | study_id)

```

```{r moderator_analysis_NT_type.1}
#Checking the levels for NT_type.1
levels(meta_tib$NT_type.1)

#Setting contrast weights (deviation coding)
calculationNT_vs_mean <-                c(0.5, 0, 0, 0, 0, 0, 0, -0.5)
cardinalityNT_vs_mean <-                c(0, 0.5, 0, 0, 0, 0, 0, -0.5)
conventional_nominativesNT.1_vs_mean <- c(0, 0, 0.5, 0, 0, 0, 0, -0.5)
countingNT_vs_mean <-                   c(0, 0, 0, 0.5, 0, 0, 0, -0.5)
number_identificationNT_vs_mean <-      c(0, 0, 0, 0, 0.5, 0, 0, -0.5)
orderingNT_vs_mean <-                   c(0, 0, 0, 0, 0, 0.5, 0, -0.5)
quantity_comparisonNT_vs_mean <-        c(0, 0, 0, 0, 0, 0, 0.5, -0.5)

contrasts(meta_tib$NT_type.1) <- cbind(
  calculationNT_vs_mean, 
  cardinalityNT_vs_mean,
  conventional_nominativesNT.1_vs_mean,
  countingNT_vs_mean,
  number_identificationNT_vs_mean,
  orderingNT_vs_mean,
  quantity_comparisonNT_vs_mean)

#contrasts(meta_tib$NT_type.1) <- contr.sum(10) - This is for sum coding - The p-values/results are all the same as deviation coding


#----------------------------------------------------------------------------------------------------
#Moderator analysis 
#3-level model
ml_meta_model.3l_mod_NT_type.1 <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                      mods = ~ NT_type.1, 
                                      random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_NT_type.1
#SIGNIFICANT RESULTS
#INTERCEPT = 	0.0462
#NT that have significantly greater effect 
#--- Cardinality (b = 0.3109, p = 0.0391)
#--- Conventional_Nominatives (b = 0.4566, p = 0.0214)
#NT that have significantly negative effect 
#--- Calculation (b = -0.2238, p = 0.0323)

#Outlier diagnostics for the 3-level model
#Cook's d 
#Cook's d at level 2
ml_meta_model.3l_mod_NT_type.1_cooks.d_lev2 <- cooks.distance(ml_meta_model.3l_mod_NT_type.1, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_NT_type.1_cooks.d_lev2
#RESULTS 
#No influential effects (but why tf is the Cook's d for a study NA??)

#Cook's d at level 3
ml_meta_model.3l_mod_NT_type.1_cooks.d_lev3 <- cooks.distance(ml_meta_model.3l_mod_NT_type.1, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% data.frame() %>% rownames_to_column(var = "study_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_NT_type.1_cooks.d_lev3
#RESULTS 
#1 influential study (casey_et_al.2018)

#DFBETAS
#Effect level 
dfbetas(ml_meta_model.3l_mod_NT_type.1, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$effect) %>% filter(abs(NT_type.1quantity_comparisonNT_vs_mean)>1)

#DFBETAS RESULTS
#There are no outliers 
#-- Intercept: All DFBETAS are below 1
#-- NT_type.1calculationNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1cardinalityNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1conventional_nominativesNT.1_vs_mean: ALL DFBETAS are below 1
#-- NT_type.1countingNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1number_identificationNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1orderingNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1quantity_comparisonNT_vs_mean: All DFBETAS are below 1

#Study level 
dfbetas(ml_meta_model.3l_mod_NT_type.1, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$study_id) %>% filter(abs(NT_type.1quantity_comparisonNT_vs_mean)>1)

#DFBETAS RESULTS
#There is 1 outlier for the intercept and the cardinality (both are casey_et_al.2018)
#-- Intercept: 1 outlier (casey_et_al.2018)
#-- NT_type.1calculationNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1cardinalityNT_vs_mean: 1 outlier (casey_et_al.2018)
#-- NT_type.1conventional_nominativesNT.1_vs_mean: ALL DFBETAS are below 1
#-- NT_type.1countingNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1number_identificationNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1orderingNT_vs_mean: All DFBETAS are below 1
#-- NT_type.1quantity_comparisonNT_vs_mean: All DFBETAS are below 1


#----------------------------------------------------------------------------------------------------
#2-level model re
ml_meta_model.2lre_mod_NT_type.1 <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                      mods = ~ NT_type.1, 
                                      random = ~ 1 | effect)
ml_meta_model.2lre_mod_NT_type.1  
#SIGNIFICANT RESULTS
#INTERCEPT = 	0.0462
#NT that have significantly greater effect 
#--- Cardinality (b = 0.3655, p = 0.0025)
#--- Conventional_Nominatives (b = 0.4486, p = 0.0001)
#NT that have significantly negative effect 
#--- Calcuation (b = -0.2900, p = 0.0224)


#2-level model
ml_meta_model.2l_mod_NT_type.1 <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                      mods = ~ NT_type.1, 
                                      random = ~ 1 | study_id)
ml_meta_model.2l_mod_NT_type.1
#SIGNIFICANT RESULTS
#INTERCEPT = 	0.0462
#NT that have significantly greater effect 
#--- Cardinality (b = 0.3365, p = 0.0009)
#--- Conventional_Nominatives (b = 0.5149,p = <.0001)
#NT that have significantly smaller effect 
#---Calculation NT (b = -0.2238, p = 0.0323)==
#--- Number Identification (b = -0.1757, p = 0.0701)

```


```{r MA_context}
#Checking the levels for NT_type.2
levels(meta_tib$MA_context)

#Setting contrast weights 
home_vs_mean <- c(1/2, 0, 0, -1/2)
lab_vs_mean <- c(0, 1/2, 0, -1/2)
school_vs_mean <- c(0, 0, 1/2, -1/2)

contrasts(meta_tib$MA_context) <- cbind(
  home_vs_mean,
  lab_vs_mean,
  school_vs_mean)

#Moderator Analysis
#----------------------------------------------------------------------------------------------------
#3-level model
ml_meta_model.3l_mod_MA_context <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                       mods = ~ MA_context, 
                                       random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_MA_context 
#RESULTS 
#Measuring in the lab has a greater effect (b = 0.3432, p = 0.017)


#Outlier diagnostics for the 3-level model
#Cook's d 
#Cook's d at level 2
ml_meta_model.3l_mod_MA_context_cooks.d_lev2 <- cooks.distance(ml_meta_model.3l_mod_MA_context, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_MA_context_cooks.d_lev2
#RESULTS 
#There are 2 outliers (mutaf_yildiz_et_al.2018a, mutaf_yildiz_et_al.2018b)

#Cook's d at level 3
ml_meta_model.3l_mod_MA_context_cooks.d_lev3 <- cooks.distance(ml_meta_model.3l_mod_MA_context, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_MA_context_cooks.d_lev3
#RESULTS 
#--- 1 outlier (boonen_et_al.2011)


```


```{r moderator_analysis_mothers}
#Mothers as cont 
#3-level model
ml_meta_model.3l_mod_mothers_cont <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                    mods = ~ mothers, 
                                    random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_mothers_cont
#RESULTS
#The proportion of mothers significantly enhanced the effect NT on MA

#Outlier
#Cook's d 
#Cook's d at level 2
ml_meta_model.3l_mod_mothers_cont_cooks.d_lev2 <- cooks.distance(ml_meta_model.3l_mod_mothers_cont, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_mothers_cont_cooks.d_lev2
#RESULTS 
#All Cook's d are below 1

#Cook's d 
#Cook's d at level 3
ml_meta_model.3l_mod_mothers_cont_cooks.d_lev3 <- cooks.distance(ml_meta_model.3l_mod_mothers_cont, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_mothers_cont_cooks.d_lev3
#RESULTS 
#There is 1 outlier (casey_et_al.2018)

#DFBETAS
#Effect level 
dfbetas(ml_meta_model.3l_mod_mothers_cont, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$effect) %>% rownames_to_column(var = "effect_id") %>% filter(abs(mothers)>1)

#DFBETAS RESULTS
#-- There are no outliers 
#-- Intercept: All DFBETAS are below 1
#-- mothers: All DFBETAS are below 1


#Study level 
dfbetas(ml_meta_model.3l_mod_mothers_cat, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$study_id) %>% filter(abs(mothers_cat1)>1)

#DFBETAS RESULTS
#There is 1 outlier for the intercept and the cardinality (both are casey_et_al.2018)
#-- Intercept: There is 1 outlier (ramani_et_al.2015)
#-- mothers_cat1: There is 1 outlier (ramani_et_al.2015)

#----------------------------------------------------------------------------------------------------
#Mothers as cat
#Create the mothers as a factor 
meta_tib_mod_mothers <- meta_tib %>% mutate(mothers_cat = ifelse(mothers > 0.8250958, "high", "low")) %>% mutate(mothers_cat = as.factor(mothers_cat)) %>% mutate(mothers_cat = fct_relevel(mothers_cat, "low", "high"))

#Setting contrast weights
#Checking the levels 
levels(meta_tib_mod_mothers$mothers_cat)
#Setting contrast weights 
mothers_cat.high_vs_low <- c(-0.5, 0.5)
contrasts(meta_tib_mod_mothers$mothers_cat) <- mothers_cat.high_vs_low

#Moderator analysis for mothers as a cat
#----------------------------------------------------------------------------------------------------
#3-level model 
ml_meta_model.3l_mod_mothers_cat <- rma.mv(yi = yi, V = vi, data = meta_tib_mod_mothers, struct = "CS", method = "REML", test = "t",
                                            mods = ~ mothers_cat, 
                                            random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_mothers_cat 
#RESULTS
#Mothers was significant (p = 0.0468)

#Regression Plot
regplot(ml_meta_model.3l_mod_mothers_cat, xlab = "Proportion of Mothers")

#Outlier
#Cook's d 
#Cook's d at level 2
ml_meta_model.3l_mod_mothers_cat_cooks.d_lev2 <- cooks.distance(ml_meta_model.3l_mod_mothers_cat, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_mothers_cat_cooks.d_lev2
#RESULTS 
#All Cook's d are below 1

#Cook's d 
#Cook's d at level 3
ml_meta_model.3l_mod_mothers_cat_cooks.d_lev3 <- cooks.distance(ml_meta_model.3l_mod_mothers_cat, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_mothers_cat_cooks.d_lev3
#RESULTS 
#There is 1 outlier (ramani)

#DFBETAS
#Effect level 
dfbetas(ml_meta_model.3l_mod_mothers_cat, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$effect) %>% rownames_to_column(var = "effect_id") %>% filter(abs(mothers_cat1)>1)

#DFBETAS RESULTS
#-- There are no outliers 
#-- Intercept: All DFBETAS are below 1
#-- mothers_cat1: All DFBETAS are below 1


#Study level 
dfbetas(ml_meta_model.3l_mod_mothers_cat, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster= meta_tib$study_id) %>% filter(abs(mothers_cat1)>1)

#DFBETAS RESULTS
#There is 1 outlier for the intercept and the cardinality (both are casey_et_al.2018)
#-- Intercept: There is 1 outlier (ramani_et_al.2015)
#-- mothers_cat1: There is 1 outlier (ramani_et_al.2015)



#----------------------------------------------------------------------------------------------------
#2-level model
ml_meta_model.2l_mod_mothers_cat <- rma.mv(yi = yi, V = vi, data = meta_tib_mod_mothers, struct = "CS", method = "REML", test = "t",
                                    mods = ~ mothers_cat, 
                                    random = ~ 1 | study_id)
ml_meta_model.2l_mod_mothers_cat
#RESULTS
#The proportion of mothers significantly enhanced the effect NT on MA


#Regression Plot
regplot(ml_meta_model.2l_mod_mothers_cat, xlab = "Proportion of Mothers")



#----------------------------------------------------------------------------------------------------
#2-level model re
ml_meta_model.2lre_mod_mothers_cat <- rma.mv(yi = yi, V = vi, data = meta_tib_mod_mothers, struct = "CS", method = "REML", test = "t",
                                    mods = ~ mothers_cat, 
                                    random = ~ 1 | effect)
ml_meta_model.2lre_mod_mothers_cat 
#RESULTS
#Mothers was significant (p = 0.0424)
regplot(ml_meta_model.2lre_mod_mothers_cat, xlab = "Proportion of Mothers")
```


```{r moderator_analysis_child_age_NT_mid}
#3-level model 
ml_meta_model.3l_mod_child_age_NT_mid <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                                mods = ~ child_age_NT_mid, 
                                                random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_child_age_NT_mid 
#RESULTS 
#--- Child age during NT has a significant effect (p = 0.0160)
regplot(ml_meta_model.3l_mod_child_age_NT_mid, xlab = "Child Age During Number Talk (Days)")


#However, the moderating effect of child age during NT may be confounded by the time between NT and MA measure
#So the time between NT and MA measure will be entered into the model
ml_meta_model.3l_mod_child_age_NT_mid.M3 <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                                mods = ~ time_between_NT_mid_MA + child_age_NT_mid, 
                                                random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_child_age_NT_mid.M3 
#RESULTS
#-- Child age during NT is still significant after entering time between NT and MA measure as covariates (p = 0.0181)


#Outlier diagnostics for the 3-level model 
#Cook's d
#Level 2
ml_meta_model.3l_mod_child_age_NT_mid_cooks.d_lev2 <- cooks.distance(ml_meta_model.3l_mod_child_age_NT_mid , progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_child_age_NT_mid_cooks.d_lev2 
#RESULTS 
#All Cook's d are below 1

#Level 3
ml_meta_model.3l_mod_child_age_NT_mid_cooks.d_lev3 <- cooks.distance(ml_meta_model.3l_mod_child_age_NT_mid , progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_child_age_NT_mid_cooks.d_lev3 
#RESULTS 
#There is 1 outier (casey_et_al.2018)


#DFBETA
#Level 2
dfbetas(ml_meta_model.3l_mod_child_age_NT_mid, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% rownames_to_column(var = "effect_id") %>% filter(abs(child_age_NT_mid)>1)
#DFBETAS RESULTS
#-- Intercept: All DFBETAS are below 1
#-- child_age_NT_mid: All DFBETAS are below 1

#Level 3
dfbetas(ml_meta_model.3l_mod_child_age_NT_mid, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% rownames_to_column(var = "effect_id") %>% filter(abs(child_age_NT_mid)>1)
#DFBETAS RESULTS
#-- Intercept: There is 1 outlier (casey_et_al.2018)
#-- child_age_NT_mid: There is 1 outlier (casey_et_al.2018)

#OVERALL OUTLIER ANALYSIS RESULT
#-- No outlier problems 
#Moderator analysis for child age during NT


#----------------------------------------------------------------------------------------------------
#2-level model 
ml_meta_model.2l_mod_child_age_NT_mid.M1 <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                                mods = ~ child_age_NT_mid, 
                                                random = ~ 1 | study_id)
ml_meta_model.2l_mod_child_age_NT_mid.M1
#RESULTS
#Child age during NT has a significant effect (p = 0.0091)

#Regression Plot
regplot(ml_meta_model.2l_mod_child_age_NT_mid.M1, xlab = "Child Age During Number Talk (Days)")


#----------------------------------------------------------------------------------------------------
#2-level model re
ml_meta_model.2lre_mod_child_age_NT_mid <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                                mods = ~ child_age_NT_mid, 
                                                random = ~ 1 | effect)
ml_meta_model.2lre_mod_child_age_NT_mid
#RESULTS 
#--- Child age during NT has a significant effect (p = 0.0149)
regplot(ml_meta_model.2lre_mod_child_age_NT_mid, xlab = "Child Age During Number Talk (Days)")




```

```{r NT_context}
#Checking the levels
levels(meta_tib$NT_context)

#Setting contrast weights 
NThome_vs_mean <-   c(1/2, 0, 0, -1/2)
NTlab_vs_mean <-    c(0, 1/2, 0, -1/2)
NTschool_vs_mean <- c(0, 0, 1/2, -1/2)

contrasts(meta_tib$NT_context) <- cbind(
  NThome_vs_mean,
  NTlab_vs_mean,
  NTschool_vs_mean)


#Moderator analysis 
#----------------------------------------------------------------------------------------------------
#3-level regression
ml_meta_model.3l_mod_NT_context <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                       mods = ~ NT_context, 
                                       random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_NT_context
#RESULTS 
#No significant results 
#But note that home shows a positive trend (b = 0.1937, p = 0.0996)

#Outliers 
#Cook's d 
#Level 2
ml_meta_model.3l_mod_NT_context_cooks.d_lev2 <- cooks.distance(ml_meta_model.3l_mod_NT_context , progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_NT_context_cooks.d_lev2
#RESULTS 
#All Cook's distances are below 0

#Level 3
ml_meta_model.3l_mod_NT_context_cooks.d_lev3 <- cooks.distance(ml_meta_model.3l_mod_NT_context , progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% data.frame() %>% rownames_to_column(var = "study_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_NT_context_cooks.d_lev3
#RESULTS
#There is 1 outlier (mutaf_yildiz_et_al.2018)


#DFBETA
#Level 2
dfbetas(ml_meta_model.3l_mod_NT_context, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% rownames_to_column(var = "effect_id") %>% filter(abs(NT_contextNTschool_vs_mean)>1)
#DFBETAS RESULTS
#-- Intercept: All DFBETAS are below 1
#-- NT_contextNThome_vs_mean: All DFBETAS are below 1
#-- NT_contextNTlab_vs_mean: All DFBETAS are below 1
#-- NT_contextNTschool_vs_mean: All DFBETAS are below 1

#Level 3
dfbetas(ml_meta_model.3l_mod_NT_context, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% rownames_to_column(var = "study_id") %>% filter(abs(NT_contextNTschool_vs_mean)>1)
#DFBETAS RESULTS
#-- Intercept: All DFBETAS are below 1
#-- NT_contextNThome_vs_mean: There is 1 outlier (mutaf_yildiz_et_al.2018)
#-- NT_contextNTlab_vs_mean: All DFBETAS are below 1
#-- NT_contextNTschool_vs_mean: All DFBETAS are below 1




#----------------------------------------------------------------------------------------------------
#2-level model re
ml_meta_model.2lre_mod_NT_context <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                       mods = ~ NT_context, 
                                       random = ~ 1 | effect)
ml_meta_model.2lre_mod_NT_context
#RESULTS 
#No significant results 
#But note that home shows a positive trend (b = 0.1937, p = 0.0996)

#----------------------------------------------------------------------------------------------------
#2-level model
ml_meta_model.2l_mod_NT_context <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                       mods = ~ NT_context, 
                                       random = ~ 1 | study_id)
ml_meta_model.2l_mod_NT_context
#RESULTS 
#No significant results 
#But note that home shows a positive trend (b = 0.2134, p = 0.0838)

```

```{r MA_measure}
#Checking the levels for MA_measure
levels(meta_tib$MA_measure)

#Setting contrast weights (deviation coding)
calculationMA_vs_mean <-             c(0.5, 0, 0, 0, 0, 0, 0, -0.5)
cardinalityMA_vs_mean <-             c(0, 0.5, 0, 0, 0, 0, 0, -0.5)
countingMA_vs_mean <-                c(0, 0, 0.5, 0, 0, 0, 0, -0.5)
number_identificationMA_vs_mean <-   c(0, 0, 0, 0.5, 0, 0, 0, -0.5)
number_knowledgeMA_vs_mean <-        c(0, 0, 0, 0, 0.5, 0, 0, -0.5)
number_line_estimation_MA_vs_mean <- c(0, 0, 0, 0, 0, 0.5, 0, -0.5)
quantity_comparisonMA_vs_mean <-     c(0, 0, 0, 0, 0, 0, 0.5, -0.5)

contrasts(meta_tib$MA_measure) <- cbind(
  calculationMA_vs_mean, 
  cardinalityMA_vs_mean,
  countingMA_vs_mean,
  number_identificationMA_vs_mean, 
  number_knowledgeMA_vs_mean,
  number_line_estimation_MA_vs_mean,
  quantity_comparisonMA_vs_mean)

#contrasts(meta_tib$NT_type.1) <- contr.sum(10) - This is for sum coding - The p-values/results are all the same as with my manual coding (which was deviation coding)

#Moderator analysis 
#----------------------------------------------------------------------------------------------------
#3-level model
ml_meta_model.3l_mod_MA_measure <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                      mods = ~ MA_measure, 
                                      random = ~ 1 | study_id/effect)
ml_meta_model.3l_mod_MA_measure
#RESULTS 
#No significant results 
#But note that calculation NT show a positive trend (b = -0.4919, 0.0745)


#Outliers 
#Cook's d 
#Level 2
ml_meta_model.3l_mod_MA_measure_cooks.d_lev2 <- cooks.distance(ml_meta_model.3l_mod_MA_measure, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% data.frame() %>% rownames_to_column(var = "effect_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_MA_measure_cooks.d_lev2
#RESULTS
#There are 6 outliers (levine_et_al.2010a, ramani_et_al.2015g, gibson_et_al.2020b, gibson_et_al.2020a, mutaf_yildiz_et_al.2018b, mutaf_yildiz_et_al.2018a)
#levine_et_al.2010a	4.6481488546			


#Level 3
ml_meta_model.3l_mod_MA_measure_cooks.d_lev3 <- cooks.distance(ml_meta_model.3l_mod_MA_measure, progbar=FALSE, reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% data.frame() %>% rownames_to_column(var = "study_id") %>% rename(., cooks.d = .) %>% arrange(desc(cooks.d))
ml_meta_model.3l_mod_MA_measure_cooks.d_lev3
#RESULTS
#There is 1 outlier (mutaf_yildiz_et_al.2018)
#There are 4 outliers (ramani_et_al.2015, levine_et_al.2010, zippert_et_al.2019, boonen_et_al.2011)



#DFBETA
#Level 2
dfbetas(ml_meta_model.3l_mod_MA_measure, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$effect) %>% rownames_to_column(var = "effect_id") %>% filter(abs(MA_measurecalculationMA_vs_mean)>1)
#DFBETAS RESULTS
#-- Intercept: All DFBETAS are below 1
#-- MA_measurecalculationMA_vs_mean

intrcpt
<dbl>
MA_measurecalculationMA_vs_mean
<dbl>
MA_measurecardinalityMA_vs_mean
<dbl>
MA_measurecountingMA_vs_mean
<dbl>
  MA_measurenumber_identificationMA_vs_mean
<dbl>
MA_measurenumber_knowledgeMA_vs_mean
<dbl>
MA_measurenumber_line_estimation_MA_vs_mean
<dbl>
<dbl>
MA_measurenumber_line_estimation_MA_vs_mean
<dbl>
MA_measurequantity_comparisonMA_vs_mean
<dbl>

#Level 3
dfbetas(ml_meta_model.3l_mod_NT_context, progbar=FALSE,reestimate=TRUE, parallel="no", ncpus=1, cluster = meta_tib$study_id) %>% rownames_to_column(var = "study_id") %>% filter(abs(NT_contextNTschool_vs_mean)>1)
#DFBETAS RESULTS
#-- Intercept: All DFBETAS are below 1
#-- NT_contextNThome_vs_mean: There is 1 outlier (mutaf_yildiz_et_al.2018)
#-- NT_contextNTlab_vs_mean: All DFBETAS are below 1
#-- NT_contextNTschool_vs_mean: All DFBETAS are below 1


#----------------------------------------------------------------------------------------------------
#2-level model
ml_meta_model.2l_mod_MA_measure <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                      mods = ~ MA_measure, 
                                      random = ~ 1 | study_id)
ml_meta_model.2l_mod_MA_measure  
#SIGNIFICANT RESULTS
#INTERCEPT = 	0.0497
#Type of MA on which NT has greater positive effect 
#-- Quantity Comparison (0.3003, p = 0.0183)
#Type of MA on which NT has negative effects
#-- Calculation (-0.5150, p = 0.0346)
#-- Number Identification (-0.2509, p = 0.0466)



#----------------------------------------------------------------------------------------------------
#2-level model b
ml_meta_model.2lre_mod_MA_measure <- rma.mv(yi = yi, V = vi, data = meta_tib, struct = "CS", method = "REML", test = "t",
                                      mods = ~ MA_measure, 
                                      random = ~ 1 | effect)
ml_meta_model.2lre_mod_MA_measure
#RESULTS 
#No significant results 
#But note that calculation NT show a positive trend (b = -0.4887, 0.0728)
```


```{r publication_bias}
#Funnel plot
funnel(ml_meta_model.3l)

#Egger's test
meta_tib2 <- meta_tib %>% mutate(se = sqrt(vi), snd = yi/se, inv.se = 1/se)

lm(snd ~ inv.se, data = meta_tib2) %>% summary()

ggplot(meta_tib2, aes(x = inv.se, y = snd)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "blue")
#RESULTS
#Egger's test indicated that there is no publication bias 
```


```{r}
(0.529 - 0.491)/0.0645

cohens.d.se <- function(d, n1, n2){
  cohens.d.se <- sqrt(
    ((n1+n2)/(n1*n2))+((d^2)/(2*(n1+n2)))
  )
  print(cohens.d.se)
}

0.5588235
cohens.d.se(d = 0.5891473, n1 = 60, n2 = 60)

0.5588235/0.1864928

pt(q = 2.996488, lower.tail = F, df = 118)

7*1
time_converter(d = 294)
time_converter(d = 276.5)
42*7
37*7

((42*7) + (37*7))/2
9.659138
```









